namespace NumbersGame
{
    internal class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Välkommen! Jag tänker på ett nummer. Kan du gissa vilket? Du får fem försök.");           //the program starts with greeting the user and then gives instructions

            Random random = new Random();                                                                                //this allows the program to randomize a number between 1 and 20
            int number = random.Next(1, 20), numberOfGuesses = 5;                                                        //and sets the number of guesses to 5
            //int number = 5, numberOfGuesses = 5;                                                                       //this allowed me to test the program and make sure it works

            string userInput = Console.ReadLine();                                                                       //now the program waits for the user's first guess
            int userNumber = Int32.Parse(userInput);                                                                     //and converts the string to an integer

            for (int i = 1; i < numberOfGuesses; i++)                                                                    //this for loop lets the user keep guessing if the guess is wrong
            {
                if (userNumber < number)                                                                                 //if the guess is lower than the number that the program generated
                {
                    Console.WriteLine("Tyvärr, du gissade för lågt!");                                                   //this is what it will type
                    userNumber = Convert.ToInt32(Console.ReadLine());
                }
                else if (userNumber > number)                                                                            //and if the guess is higher than the number that the program generated
                {
                    Console.WriteLine("Tyvärr, du gissade för högt!");                                                   //this is what it will type
                    userNumber = Convert.ToInt32(Console.ReadLine());
                }
            }

            bool correctGuess = (userNumber == number);                                                                  //this bool lets the program check if the user's guess is equal to
            CheckGuess(correctGuess);                                                                                    //the number generated by the program

        }
        static void CheckGuess(bool correctGuess)                                                                        //and this method checks the user's guess and types accordingly
        {
            string compute = correctGuess ? "Woohoo! Du klarade det!" : "Tyvärr, du lyckades inte gissa talet på fem försök!";
            Console.WriteLine(compute);
        }
        








            //Min första tanke as follows

            //Console.WriteLine("Välkommen! Jag tänker på ett nummer. Kan du gissa vilket? Du får fem försök.");

            //Random random = new Random();
            //int number = random.Next(1, 20), numberGuesses = 5;

            //string userInput = Console.ReadLine();
            //int userNumber = Int32.Parse(userInput);

            //while (userNumber != number) 
            //{
            //    if (userNumber < number)
            //    {
            //        Console.WriteLine("Tyvärr, du gissade för lågt!");
            //        userNumber = Convert.ToInt32(Console.ReadLine());
            //    }
            //    else if (userNumber > number)
            //    {
            //        Console.WriteLine("Tyvärr, du gissade för högt!");
            //        userNumber = Convert.ToInt32(Console.ReadLine());
            //    }

            //} 
            //Console.WriteLine("Wohoo! Du klarade det!");


        
        //Min andra tanke        
        
        //Console.WriteLine("Välkommen! Jag tänker på ett nummer. Kan du gissa vilket? Du får fem försök.");

            //Random random = new Random();
            //int number = random.Next(1, 20), numberOfGuesses = 5;
            //int number = 5, numberOfGuesses = 5; //här testade jag kommentera bort random number och körde med 5

            //string userInput = Console.ReadLine();
            //int userNumber = Int32.Parse(userInput);

            //bool correctGuess = (userNumber == number);

            //for (int i = 1;  i < numberOfGuesses; i++)
            //{
            //    if (userNumber < number)
            //    {
            //        Console.WriteLine("Tyvärr, du gissade för lågt!");
            //        userNumber = Convert.ToInt32(Console.ReadLine());
            //    }
            //    else if (userNumber > number)
            //    {
            //        Console.WriteLine("Tyvärr, du gissade för högt!");
            //        userNumber = Convert.ToInt32(Console.ReadLine());
            //    }
               //else if (userNumber == number)
                //{
                //    Console.WriteLine("Woohoo! Du klarade det!");
                //    break;
                //}
                //else if (i == numberOfGuesses)
                //{
                //    Console.WriteLine("Tyvärr, du lyckades inte gissa talet på fem försök!");
                //    break;
                //}
                
    }
}